### ISSUE TITLE
Archive this repository (and write up a blog post?)

### ISSUE THREAD

**Issue by choldgraf** [jupyter-incubator/nb2kg#49]
In a governance meeting @lresende mentioned that this repository is now merged into Jupyter Notebook 6.0. I also see this is noted in the README.

Are bugfixes / patches planned for this repo? If not, could we archive it?

As an aside - it'd be cool to see a blog post about nb2kg's journey into Notebook 6.0 :-)

**Comment by lresende** [comment]
> In a governance meeting @lresende mentioned that this repository is now merged into Jupyter Notebook 6.0. I also see this is noted in the README.
> 
> Are bugfixes / patches planned for this repo? If not, could we archive it?
> 

Things should be redirected to jupyter notebook or jupyter server repositories

> As an aside - it'd be cool to see a blog post about nb2kg's journey into Notebook 6.0 :-)

We could look into that, but it might be a simple blog post duplicating what is on the documentation

**Comment by kevin-bates** [comment]
(I was going to create a new issue regarding archival, but found this one - so piggybacking.  However, I think it's a little late for the blog post portion of things.)

Since Notebook 6.0, the functionality provided by this server extension has been built into notebook (as well as jupyter server) and is practically obsolete.  More importantly (IMO), there is a current dependabot alert stating that the minimum version of notebook should be increased to `6.4.12` despite the fact that its dependency on notebook is stated as `notebook>=4.2.0,<6.0`.  Add to that, this repository is not actively maintained.  As a result, I think it's worth asking (again) whether this repository should be archived.

I posted [this question](https://github.com/jupyter-server/team-compass/issues/42) in the Jupyter Server team compass and we will be polling the council members on whether archival is warranted, but, as also discussed in today's [server meeting](https://github.com/jupyter-server/team-compass/issues/15#issuecomment-1319024800) felt an issue should be opened here stating this intention for those that may be reliant on this repository.  Since an issue already existed, I'm using commenting here.

@jweill-aws, @blink1073 thought it would be a good idea to bring this to your attention since your company may still be using older versions (< 6.0) of notebook.  Do you know of any reasons why archiving this repository would be problematic (for your company or otherwise, given your recent involvement with the notebook project)?

Please comment here or on the previously referenced team-compass issue if anyone else has an opinion.

Assuming there are no objections, I would like to archive this repository in the last week of November (although that's probably optimistic).

**Comment by JasonWeill** [comment]
@kevin-bates Earlier this year, I told my colleagues about the upcoming deprecation of Notebook 5; once Notebook 7, Notebook 5 officially leaves maintenance. For our internal and supported externally-facing services, Notebook 6 is now being used.

**Comment by kevin-bates** [comment]
Looks like we will go ahead with the archiving of this repo.  Closing.
